# Generated by Django 2.0.4 on 2018-04-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_text', models.CharField(max_length=300)),
            ],
        ),
    ]
